# Module: CaptacionPsto
# Document : modules\CaptacionPsto\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 25.04.2012 12:27:39
#
---
CaptacionPsto:
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: CaptacionPsto
  id_video: captacionpsto
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: CaptacionPsto
  table: captacion_psto
  primarykey: Id
  records_per_page: 15
  order_by: Id
  linkBy: IDCaptacion
  search_default: Id
  referenced_entities:
    -
      entity: CaptacionTipos
  columns:
    -
      title: Id
      field: Id
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
    -
      title: IDCaptacion
      field: IDCaptacion
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      aditional_filter:
        order: 1
        caption: IDCaptacion
        entity: CaptacionTipos
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: Ano
      field: Ano
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: Presupuesto
      field: Presupuesto
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
