# Module: Articulos
# Document : modules\Articulos\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 11.04.2012 12:31:18
#
---
Articulos:
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Artículos
  id_video: articulos
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: Articulos
  table: articulos
  primarykey: IDArticulo
  records_per_page: 15
  order_by:
    -
      title: Código a-z
      criteria: Codigo ASC
    -
      title: Código z-a
      criteria: Codigo DESC
    -
      title: Descripción a-z
      criteria: Descripcion ASC
    -
      title: Descripción z-a
      criteria: Descripcion DESC
  search_default: IDArticulo
  referenced_entities:
    -
      entity: Familias
    -
      entity: TiposVenta
  columns:
    -
      title: IDArticulo
      field: IDArticulo
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
    -
      title: Código
      field: Codigo
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: NO
        type: string
        length: 25
        min: null
        max: null
        message: Valor Requerido
    -
      title: Descripción
      field: Descripcion
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: NO
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: Familia
      field: IDFamilia
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 1
        caption: Familia
        entity: Familias
        method: fetchAll
        params: Familia
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 15
        min: 1
        max: 9999
        message: Valor Requerido
    -
      title: Venta
      field: IDVenta
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 2
        caption: Tipo de Venta
        entity: TiposVenta
        method: fetchAll
        params: TipoVenta
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 20
        min: 1
        max: 9999
        message: Valor Requerido
    -
      title: Numero de Días
      field: NumeroDias
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: NO
        type: decimal
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: % Alta
      field: PorcentajeAlta
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: % Renovación
      field: PorcentajeRenovacion
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: Características
      field: Caracteristicas
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: YES
        type: string
        length:
        min: null
        max: null
        message: Valor Requerido
    -
      title: Udad Medida Básica
      field: UMB
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 4
        min: 1
        max: 9999
        message: Valor Requerido
    -
      title: Udad Medida Compra
      field: UMC
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 4
        min: 1
        max: 9999
        message: Valor Requerido
    -
      title: CUMC
      field: CUMC
      filter: NO
      list: NO
      form: NO
      link:
        route: null
        param: null
        title: null
        target: null
      default: 1.00
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: Udad Medida Almacen
      field: UMA
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 4
        min: 1
        max: 9999
        message: Valor Requerido
    -
      title: CUMA
      field: CUMA
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 1.00
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
    -
      title: Udad Medida Venta
      field: UMV
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 4
        min: 1
        max: 9999
        message: Valor Requerido
    -
      title: CUMV
      field: CUMV
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
      default: 1.00
      validator:
        nullable: NO
        type: decimal
        length: 5
        min: null
        max: null
        message: Valor Requerido
