# Module: ContratosHistorico
# Document : modules\ContratosHistorico\config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: INFORMATICA ALBATRONIC SL
# @date 08.08.2012 18:49:32
#
---
ContratosHistorico:
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: ContratosHistorico
  id_video: contratoshistorico
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: ContratosHistorico
  table: contratos_historico
  primarykey: Id
  linkBy: IDContrato
  records_per_page: 9999
  order_by: Id
  search_default: Id
  referenced_entities:
  columns:
    -
      title: Id
      field: Id
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
    -
      title: IDContrato
      field: IDContrato
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: Operacion
      field: IDOperacion
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: Fecha
      field: Fecha
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      aditional_filter:
        order: 1
        caption: Fecha
        type: range
        operator: >=
      validator:
        nullable: NO
        type: date
        length: 10
        min: null
        max: null
        message: Valor Requerido
    -
      title: Descripcion
      field: Descripcion
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: NO
        type: string
        length: 255
        min: null
        max: null
        message: Valor Requerido
    -
      title: Entidad
      field: Entidad
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: YES
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDEntidad
      field: IDEntidad
      filter: NO
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default:
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
