# Module: CaptacionTipos
# Document : modules\CaptacionTipos\config.yml
#
# @author Sergio Pérez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 25.04.2012 12:27:12
#
---
CaptacionTipos:
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Tipos de captación de clientes
  id_video: captaciontipos
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: CaptacionTipos
  table: captacion_tipos
  primarykey: IDCaptacion
  records_per_page: 15
  order_by:
    -
      title: Captación a-z
      criteria: Captacion ASC
    -
      title: Captación z-a
      criteria: Captacion DESC
  search_default: IDCaptacion
  referenced_entities:
  columns:
    -
      title: IDCaptacion
      field: IDCaptacion
      filter: NO
      list: NO
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
    -
      title: Tipo Captación
      field: Captacion
      filter: YES
      list: YES
      form: YES
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      validator:
        nullable: NO
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
